name: weather_app
description: Weather App.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  retrofit: ^3.0.1+1
  freezed_annotation: ^1.1.0
  auto_route: ^3.2.3+1
  get_it: ^7.2.0
  injectable: ^1.5.3
  card_swiper: ^2.0.1
  fl_chart: ^0.45.0
  geolocator: ^8.2.0
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.0.4
  loading_animation_widget: ^1.1.0+1
  dartz: ^0.10.1
  hive: ^2.0.5
  json_annotation: ^4.4.0
  hive_flutter: ^1.1.0
  equatable: ^2.0.3
  pretty_dio_logger: ^1.1.1
  geocoding: ^2.0.2
  intl: ^0.17.0
  material_floating_search_bar_2: 0.5.0 
  
  file: ^6.1.4

dependency_overrides:
  analyzer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_gen: ^4.1.5
  auto_route_generator: ^3.2.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  bloc_test: ^9.0.2
  mockito: ^5.1.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/weather_app_icon.png"



flutter:

  
  
  
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  
  
